In [ ]:
##+========================================================Charging Dashboard Project==========================================================

In [ ]:
##===============================================================Load Dataset==================================================================

In [1]:
import pandas as pd 
import numpy as np
import streamlit as st 
import plotly.express as px
import plotly.graph_objects as go

In [2]:
df = pd.read_csv("ChargingRecords.csv")
df

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,15-09-2022,20:54:02,15-09-2022,23:59:13,15-09-2022 20:54,15-09-2022 23:59,185,20.36
1,0,1,1,hotel,0,14-09-2022,20:01:05,14-09-2022,21:31:04,14-09-2022 20:01,14-09-2022 21:31,90,10.19
2,0,1,1,hotel,0,14-09-2022,18:54:30,14-09-2022,19:54:29,14-09-2022 18:54,14-09-2022 19:54,60,6.78
3,0,1,1,hotel,0,29-09-2022,18:32:51,30-09-2022,00:16:42,29-09-2022 18:32,30-09-2022 00:16,344,37.65
4,0,1,1,hotel,0,25-09-2022,19:30:15,26-09-2022,00:30:14,25-09-2022 19:30,26-09-2022 00:30,300,33.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72851,2155,2649,0,public institution,0,27-01-2022,09:54:44,27-01-2022,09:58:57,27-01-2022 09:54,27-01-2022 09:58,4,0.50
72852,2379,2670,0,sightseeing,1,31-10-2021,14:52:11,31-10-2021,15:20:28,31-10-2021 14:52,31-10-2021 15:20,28,16.53
72853,2388,2670,0,sightseeing,1,03-10-2021,13:52:14,03-10-2021,14:32:13,03-10-2021 13:52,03-10-2021 14:32,40,12.20
72854,2388,2671,0,company,1,18-11-2021,11:37:44,18-11-2021,11:45:37,18-11-2021 11:37,18-11-2021 11:45,8,3.80
72855,2388,2671,0,company,1,30-10-2021,17:29:02,30-10-2021,17:36:47,30-10-2021 17:29,30-10-2021 17:36,8,3.67

In [ ]:
##============================================================Data Cheking=============================================================

In [3]:
df.head()

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,15-09-2022,20:54:02,15-09-2022,23:59:13,15-09-2022 20:54,15-09-2022 23:59,185,20.36
1,0,1,1,hotel,0,14-09-2022,20:01:05,14-09-2022,21:31:04,14-09-2022 20:01,14-09-2022 21:31,90,10.19
2,0,1,1,hotel,0,14-09-2022,18:54:30,14-09-2022,19:54:29,14-09-2022 18:54,14-09-2022 19:54,60,6.78
3,0,1,1,hotel,0,29-09-2022,18:32:51,30-09-2022,00:16:42,29-09-2022 18:32,30-09-2022 00:16,344,37.65
4,0,1,1,hotel,0,25-09-2022,19:30:15,26-09-2022,00:30:14,25-09-2022 19:30,26-09-2022 00:30,300,33.81

In [4]:
df.tail()

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
72851,2155,2649,0,public institution,0,27-01-2022,09:54:44,27-01-2022,09:58:57,27-01-2022 09:54,27-01-2022 09:58,4,0.50
72852,2379,2670,0,sightseeing,1,31-10-2021,14:52:11,31-10-2021,15:20:28,31-10-2021 14:52,31-10-2021 15:20,28,16.53
72853,2388,2670,0,sightseeing,1,03-10-2021,13:52:14,03-10-2021,14:32:13,03-10-2021 13:52,03-10-2021 14:32,40,12.20
72854,2388,2671,0,company,1,18-11-2021,11:37:44,18-11-2021,11:45:37,18-11-2021 11:37,18-11-2021 11:45,8,3.80
72855,2388,2671,0,company,1,30-10-2021,17:29:02,30-10-2021,17:36:47,30-10-2021 17:29,30-10-2021 17:36,8,3.67

In [6]:
df.shape

(72856, 13)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72856 entries, 0 to 72855
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72856 non-null  int64
 1   ChargerID       72856 non-null  int64
 2   ChargerCompany  72856 non-null  int64
 3   Location        72856 non-null  object
 4   ChargerType     72856 non-null  int64
 5   StartDay        72856 non-null  object
 6   StartTime       72856 non-null  object
 7   EndDay          72856 non-null  object
 8   EndTime         72856 non-null  object
 9   StartDatetime   72856 non-null  object
 10  EndDatetime     72856 non-null  object
 11  Duration        72856 non-null  int64
 12  Demand          72856 non-null  float64
dtypes: float64(1), int64(5), object(7)
memory usage: 7.2+ MB

In [10]:
df.describe()

,UserID,ChargerID,ChargerCompany,ChargerType,Duration,Demand
count,72856.000000,72856.000000,72856.000000,72856.00000,72856.000000,72856.000000
mean,338.164667,525.489212,0.627443,0.20524,151.194054,17.444445
std,553.970996,569.544469,0.483489,0.40388,146.430286,13.492728
min,0.000000,1.000000,0.000000,0.00000,-29.000000,0.010000
25%,0.000000,107.000000,0.000000,0.00000,40.000000,7.530000
50%,62.000000,301.000000,1.000000,0.00000,112.000000,14.100000
75%,407.000000,738.000000,1.000000,0.00000,202.000000,23.200000
max,2501.000000,2671.000000,1.000000,1.00000,1573.000000,97.000000

In [14]:
df.columns

Index(['UserID', 'ChargerID', 'ChargerCompany', 'Location', 'ChargerType',
       'StartDay', 'StartTime', 'EndDay', 'EndTime', 'StartDatetime',
       'EndDatetime', 'Duration', 'Demand'],
      dtype='object')

In [23]:
df.dtypes

UserID              int64
ChargerID           int64
ChargerCompany      int64
Location           object
ChargerType         int64
StartDay           object
StartTime          object
EndDay             object
EndTime            object
StartDatetime      object
EndDatetime        object
Duration            int64
Demand            float64
dtype: object

In [ ]:
##==============================================================Data Clening===========================================================

In [24]:
df.isnull().sum()

UserID            0
ChargerID         0
ChargerCompany    0
Location          0
ChargerType       0
StartDay          0
StartTime         0
EndDay            0
EndTime           0
StartDatetime     0
EndDatetime       0
Duration          0
Demand            0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(13)

In [26]:
df[df.duplicated()]

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
28857,329,214,1,public area,0,12-02-2022,07:22:40,12-02-2022,15:44:27,12-02-2022 07:22,12-02-2022 15:44,502,54.34
28859,329,214,1,public area,0,15-02-2022,19:29:42,15-02-2022,23:03:11,15-02-2022 19:29,15-02-2022 23:03,213,23.68
28862,329,214,1,public area,0,17-02-2022,18:53:55,18-02-2022,03:38:13,17-02-2022 18:53,18-02-2022 03:38,524,58.06
40670,461,371,1,apartment,0,22-02-2022,16:17:01,22-02-2022,21:38:44,22-02-2022 16:17,22-02-2022 21:38,322,37.74
51499,276,640,0,company,1,26-02-2022,09:23:02,26-02-2022,10:03:07,26-02-2022 09:23,26-02-2022 10:03,40,15.04
56653,1956,854,0,public area,1,15-02-2022,06:19:05,15-02-2022,07:36:38,15-02-2022 06:19,15-02-2022 07:36,78,49.07
57316,582,900,0,public parking lot,1,24-02-2022,09:49:03,24-02-2022,10:29:04,24-02-2022 09:49,24-02-2022 10:29,40,18.29
60212,228,1045,0,public area,1,26-02-2022,18:24:08,26-02-2022,18:39:59,26-02-2022 18:24,26-02-2022 18:39,16,10.54
61146,615,1094,0,hotel,0,05-02-2022,20:36:57,05-02-2022,22:40:37,05-02-2022 20:36,05-02-2022 22:40,124,13.93
64958,1146,1341,0,hotel,0,04-02-2022,18:13:23,05-02-2022,01:00:26,04-02-2022 18:13,05-02-2022 01:00,407,32.11
66121,156,1450,0,public parking lot,1,21-02-2022,12:03:16,21-02-2022,12:43:16,21-02-2022 12:03,21-02-2022 12:43,40,13.56
71101,1955,2086,0,public area,1,24-02-2022,16:37:14,24-02-2022,16:52:12,24-02-2022 16:37,24-02-2022 16:52,15,7.35
72780,1858,2605,0,apartment,0,27-02-2022,22:12:35,28-02-2022,04:29:06,27-02-2022 22:12,28-02-2022 04:29,377,22.60

In [28]:
df = df.drop_duplicates()
df

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,15-09-2022,20:54:02,15-09-2022,23:59:13,15-09-2022 20:54,15-09-2022 23:59,185,20.36
1,0,1,1,hotel,0,14-09-2022,20:01:05,14-09-2022,21:31:04,14-09-2022 20:01,14-09-2022 21:31,90,10.19
2,0,1,1,hotel,0,14-09-2022,18:54:30,14-09-2022,19:54:29,14-09-2022 18:54,14-09-2022 19:54,60,6.78
3,0,1,1,hotel,0,29-09-2022,18:32:51,30-09-2022,00:16:42,29-09-2022 18:32,30-09-2022 00:16,344,37.65
4,0,1,1,hotel,0,25-09-2022,19:30:15,26-09-2022,00:30:14,25-09-2022 19:30,26-09-2022 00:30,300,33.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72851,2155,2649,0,public institution,0,27-01-2022,09:54:44,27-01-2022,09:58:57,27-01-2022 09:54,27-01-2022 09:58,4,0.50
72852,2379,2670,0,sightseeing,1,31-10-2021,14:52:11,31-10-2021,15:20:28,31-10-2021 14:52,31-10-2021 15:20,28,16.53
72853,2388,2670,0,sightseeing,1,03-10-2021,13:52:14,03-10-2021,14:32:13,03-10-2021 13:52,03-10-2021 14:32,40,12.20
72854,2388,2671,0,company,1,18-11-2021,11:37:44,18-11-2021,11:45:37,18-11-2021 11:37,18-11-2021 11:45,8,3.80
72855,2388,2671,0,company,1,30-10-2021,17:29:02,30-10-2021,17:36:47,30-10-2021 17:29,30-10-2021 17:36,8,3.67

In [29]:
df.duplicated().sum()

np.int64(0)

In [ ]:
##=================================================================Categorical Columns================================================

In [31]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}")
    print(df[col].unique())

Location
['hotel' 'company' 'apartment' 'resort' 'public area' 'public institution'
 'restaurant' 'accommodation' 'golf' 'sightseeing' 'market' 'camping'
 'public parking lot' 'bus garage']

StartDay
['15-09-2022' '14-09-2022' '29-09-2022' '25-09-2022' '24-09-2022'
 '11-08-2022' '10-08-2022' '09-08-2022' '07-08-2022' '06-08-2022'
 '05-08-2022' '23-08-2022' '22-08-2022' '19-08-2022' '18-08-2022'
 '17-08-2022' '02-07-2022' '03-07-2022' '05-07-2022' '08-07-2022'
 '14-07-2022' '27-07-2022' '07-06-2022' '09-06-2022' '10-06-2022'
 '18-06-2022' '23-06-2022' '08-05-2022' '09-05-2022' '12-05-2022'
 '14-05-2022' '15-05-2022' '16-05-2022' '23-05-2022' '27-05-2022'
 '08-04-2022' '14-04-2022' '16-04-2022' '27-04-2022' '01-03-2022'
 '02-03-2022' '03-03-2022' '10-03-2022' '12-03-2022' '13-03-2022'
 '18-03-2022' '30-03-2022' '31-03-2022' '01-02-2022' '04-02-2022'
 '11-02-2022' '14-02-2022' '20-02-2022' '27-02-2022' '27-01-2022'
 '07-12-2021' '17-12-2021' '20-12-2021' '24-12-2021' '08-09-2022'
 '22-09-2022' '14-08-2022' '04-08-2022' '03-08-2022' '02-08-2022'
 '24-08-2022' '21-08-2022' '20-08-2022' '16-08-2022' '29-07-2022'
 '25-07-2022' '22-07-2022' '21-07-2022' '18-07-2022' '07-07-2022'
 '04-07-2022' '01-07-2022' '03-06-2022' '08-06-2022' '12-06-2022'
 '14-06-2022' '21-06-2022' '01-05-2022' '03-05-2022' '20-05-2022'
 '25-05-2022' '29-05-2022' '30-05-2022' '01-04-2022' '06-04-2022'
 '25-04-2022' '29-04-2022' '27-03-2022' '29-03-2022' '18-09-2022'
 '17-06-2022' '09-02-2022' '28-07-2022' '13-09-2022' '01-08-2022'
 '07-09-2022' '11-09-2022' '19-12-2021' '12-09-2022' '12-02-2022'
 '12-07-2022' '10-09-2022' '30-07-2022' '16-12-2021' '20-03-2022'
 '28-06-2022' '29-06-2022' '30-06-2022' '13-05-2022' '28-05-2022'
 '31-07-2022' '10-05-2022' '07-02-2022' '23-02-2022' '28-09-2022'
 '19-06-2022' '10-07-2022' '06-06-2022' '21-03-2022' '23-09-2022'
 '23-04-2022' '21-09-2022' '25-02-2022' '17-09-2022' '16-09-2022'
 '15-08-2022' '15-04-2022' '16-07-2022' '19-04-2022' '20-04-2022'
 '13-08-2022' '12-08-2022' '08-08-2022' '07-05-2022' '06-05-2022'
 '05-05-2022' '03-02-2022' '29-01-2022' '16-02-2022' '17-02-2022'
 '17-07-2022' '05-03-2022' '25-08-2022' '05-04-2022' '26-07-2022'
 '26-12-2021' '27-12-2021' '18-02-2022' '19-02-2022' '20-07-2022'
 '19-05-2022' '12-04-2022' '26-06-2022' '18-12-2021' '24-07-2022'
 '24-06-2022' '15-12-2021' '23-07-2022' '08-02-2022' '15-02-2022'
 '24-02-2022' '11-07-2022' '18-04-2022' '24-04-2022' '15-07-2022'
 '22-06-2022' '13-07-2022' '09-07-2022' '26-04-2022' '18-05-2022'
 '11-06-2022' '31-05-2022' '04-04-2022' '25-06-2022' '01-06-2022'
 '04-06-2022' '04-05-2022' '24-05-2022' '14-03-2022' '07-03-2022'
 '10-04-2022' '08-03-2022' '11-05-2022' '22-05-2022' '23-03-2022'
 '17-04-2022' '21-04-2022' '19-03-2022' '13-04-2022' '07-04-2022'
 '16-03-2022' '05-02-2022' '24-03-2022' '10-02-2022' '26-03-2022'
 '09-03-2022' '22-03-2022' '02-02-2022' '21-12-2021' '22-02-2022'
 '06-02-2022' '26-02-2022' '28-02-2022' '30-01-2022' '28-01-2022'
 '17-11-2021' '25-12-2021' '25-11-2021' '29-11-2021' '24-11-2021'
 '04-11-2021' '06-09-2022' '01-09-2022' '19-09-2022' '28-08-2022'
 '27-08-2022' '02-09-2022' '26-08-2022' '27-09-2022' '31-08-2022'
 '29-08-2022' '26-09-2022' '20-09-2022' '06-07-2022' '19-07-2022'
 '02-06-2022' '02-05-2022' '17-05-2022' '21-05-2022' '26-05-2022'
 '11-04-2022' '30-04-2022' '04-03-2022' '06-03-2022' '13-02-2022'
 '31-12-2021' '01-01-2022' '02-01-2022' '03-01-2022' '04-01-2022'
 '06-01-2022' '11-01-2022' '12-01-2022' '13-01-2022' '14-01-2022'
 '15-01-2022' '16-01-2022' '17-01-2022' '18-01-2022' '19-01-2022'
 '20-01-2022' '21-01-2022' '23-01-2022' '24-01-2022' '31-01-2022'
 '30-11-2021' '01-12-2021' '05-12-2021' '06-12-2021' '08-12-2021'
 '10-12-2021' '14-12-2021' '22-12-2021' '23-12-2021' '28-12-2021'
 '29-12-2021' '02-11-2021' '03-11-2021' '10-11-2021' '11-11-2021'
 '18-11-2021' '20-11-2021' '23-11-2021' '28-11-2021' '01-10-2021'
 '04-10-2021' '06-10-2021' '08-10-2021' '10-10-2021' '13-10-2021'
 '17-10-2021' '20-10-2021' '26-10-2021' '29-10-2021' '11-03-2022'
 '30-09-2022' '09-09-2022' '30-12-2021' '22-11-2021' '14-10-2021'
 '09-12-2021' '11-12-2021' '24-10-2021' '08-01-2022' '09-01-2022'
 '05-01-2022' '22-04-2022' '25-03-2022' '10-01-2022' '25-01-2022'
 '02-12-2021' '01-11-2021' '06-11-2021' '09-11-2021' '21-11-2021'
 '16-06-2022' '26-11-2021' '27-06-2022' '03-04-2022' '28-10-2021'
 '12-11-2021' '05-11-2021' '11-10-2021' '13-06-2022' '15-06-2022'
 '02-04-2022' '15-11-2021' '16-11-2021' '15-03-2022' '13-12-2021'
 '27-11-2021' '14-11-2021' '18-10-2021' '19-10-2021' '12-10-2021'
 '13-11-2021' '28-03-2022' '21-10-2021' '22-10-2021' '15-10-2021'
 '16-10-2021' '22-01-2022' '25-10-2021' '27-10-2021' '07-10-2021'
 '09-10-2021' '02-10-2021' '26-01-2022' '30-08-2022' '08-11-2021'
 '05-06-2022' '17-03-2022' '03-12-2021' '23-10-2021' '03-09-2022'
 '20-06-2022' '07-01-2022' '12-12-2021' '19-11-2021' '05-10-2021'
 '30-10-2021' '09-04-2022' '28-04-2022' '07-11-2021' '03-10-2021'
 '31-10-2021' '04-09-2022' '21-02-2022' '04-12-2021' '05-09-2022'
 '30-09-2021']

StartTime
['20:54:02' '20:01:05' '18:54:30' ... '22:45:07' '19:12:17' '14:52:11']

EndDay
['15-09-2022' '14-09-2022' '30-09-2022' '26-09-2022' '24-09-2022'
 '11-08-2022' '09-08-2022' '07-08-2022' '05-08-2022' '24-08-2022'
 '23-08-2022' '22-08-2022' '19-08-2022' '18-08-2022' '17-08-2022'
 '02-07-2022' '03-07-2022' '05-07-2022' '09-07-2022' '14-07-2022'
 '27-07-2022' '28-07-2022' '07-06-2022' '09-06-2022' '10-06-2022'
 '18-06-2022' '23-06-2022' '08-05-2022' '09-05-2022' '12-05-2022'
 '14-05-2022' '15-05-2022' '17-05-2022' '23-05-2022' '27-05-2022'
 '09-04-2022' '14-04-2022' '17-04-2022' '28-04-2022' '01-03-2022'
 '02-03-2022' '03-03-2022' '11-03-2022' '12-03-2022' '13-03-2022'
 '18-03-2022' '30-03-2022' '31-03-2022' '01-02-2022' '04-02-2022'
 '11-02-2022' '14-02-2022' '20-02-2022' '27-02-2022' '27-01-2022'
 '07-12-2021' '17-12-2021' '20-12-2021' '21-12-2021' '24-12-2021'
 '08-09-2022' '29-09-2022' '23-09-2022' '14-08-2022' '04-08-2022'
 '03-08-2022' '25-08-2022' '21-08-2022' '20-08-2022' '16-08-2022'
 '30-07-2022' '25-07-2022' '22-07-2022' '21-07-2022' '18-07-2022'
 '08-07-2022' '07-07-2022' '03-06-2022' '08-06-2022' '12-06-2022'
 '15-06-2022' '21-06-2022' '01-05-2022' '04-05-2022' '20-05-2022'
 '25-05-2022' '29-05-2022' '30-05-2022' '01-04-2022' '06-04-2022'
 '08-04-2022' '25-04-2022' '29-04-2022' '27-03-2022' '29-03-2022'
 '28-02-2022' '18-09-2022' '17-06-2022' '09-02-2022' '13-09-2022'
 '01-08-2022' '07-09-2022' '11-09-2022' '19-12-2021' '12-09-2022'
 '13-02-2022' '12-07-2022' '10-09-2022' '16-12-2021' '20-03-2022'
 '28-06-2022' '30-06-2022' '13-05-2022' '28-05-2022' '31-07-2022'
 '10-05-2022' '07-02-2022' '12-02-2022' '23-02-2022' '28-09-2022'
 '20-06-2022' '10-07-2022' '21-03-2022' '25-09-2022' '24-04-2022'
 '04-07-2022' '21-09-2022' '25-02-2022' '16-09-2022' '15-08-2022'
 '15-04-2022' '16-07-2022' '19-03-2022' '19-04-2022' '20-04-2022'
 '13-08-2022' '10-08-2022' '29-07-2022' '08-08-2022' '25-12-2021'
 '07-05-2022' '06-05-2022' '02-08-2022' '23-04-2022' '03-02-2022'
 '29-01-2022' '19-06-2022' '16-02-2022' '17-02-2022' '17-07-2022'
 '05-03-2022' '05-04-2022' '26-12-2021' '27-12-2021' '19-02-2022'
 '20-07-2022' '03-05-2022' '19-05-2022' '12-04-2022' '26-06-2022'
 '18-12-2021' '26-07-2022' '24-07-2022' '24-06-2022' '15-12-2021'
 '23-07-2022' '08-02-2022' '24-02-2022' '11-07-2022' '18-04-2022'
 '15-07-2022' '01-07-2022' '22-06-2022' '06-06-2022' '29-06-2022'
 '26-04-2022' '13-04-2022' '18-05-2022' '11-06-2022' '31-05-2022'
 '04-04-2022' '25-06-2022' '01-06-2022' '04-06-2022' '24-05-2022'
 '14-03-2022' '07-03-2022' '10-04-2022' '09-03-2022' '11-05-2022'
 '22-05-2022' '05-05-2022' '16-04-2022' '23-03-2022' '21-04-2022'
 '22-04-2022' '02-04-2022' '17-03-2022' '05-02-2022' '04-03-2022'
 '24-03-2022' '10-02-2022' '26-03-2022' '10-03-2022' '08-03-2022'
 '22-03-2022' '02-02-2022' '22-02-2022' '15-02-2022' '06-02-2022'
 '26-02-2022' '30-01-2022' '28-01-2022' '17-11-2021' '25-11-2021'
 '29-11-2021' '24-11-2021' '04-11-2021' '06-09-2022' '01-09-2022'
 '19-09-2022' '17-09-2022' '28-08-2022' '26-08-2022' '03-09-2022'
 '31-08-2022' '29-08-2022' '27-08-2022' '22-09-2022' '20-09-2022'
 '12-08-2022' '06-07-2022' '13-07-2022' '19-07-2022' '02-06-2022'
 '16-05-2022' '21-05-2022' '26-05-2022' '07-04-2022' '30-04-2022'
 '06-03-2022' '01-01-2022' '02-01-2022' '03-01-2022' '04-01-2022'
 '07-01-2022' '11-01-2022' '13-01-2022' '14-01-2022' '15-01-2022'
 '16-01-2022' '17-01-2022' '18-01-2022' '19-01-2022' '20-01-2022'
 '21-01-2022' '23-01-2022' '24-01-2022' '31-01-2022' '01-12-2021'
 '05-12-2021' '06-12-2021' '08-12-2021' '10-12-2021' '14-12-2021'
 '22-12-2021' '23-12-2021' '28-12-2021' '29-12-2021' '02-11-2021'
 '03-11-2021' '10-11-2021' '11-11-2021' '18-11-2021' '20-11-2021'
 '21-11-2021' '23-11-2021' '28-11-2021' '30-11-2021' '01-10-2021'
 '04-10-2021' '06-10-2021' '08-10-2021' '10-10-2021' '13-10-2021'
 '17-10-2021' '20-10-2021' '26-10-2021' '29-10-2021' '02-09-2022'
 '30-08-2022' '09-09-2022' '30-12-2021' '22-11-2021' '14-10-2021'
 '15-10-2021' '11-04-2022' '31-12-2021' '09-12-2021' '27-09-2022'
 '12-11-2021' '11-12-2021' '24-10-2021' '08-01-2022' '09-01-2022'
 '06-01-2022' '06-08-2022' '25-03-2022' '10-01-2022' '25-01-2022'
 '02-12-2021' '01-11-2021' '06-11-2021' '09-11-2021' '27-11-2021'
 '27-06-2022' '28-10-2021' '18-02-2022' '11-10-2021' '13-06-2022'
 '05-01-2022' '02-05-2022' '15-11-2021' '16-11-2021' '15-03-2022'
 '02-10-2021' '13-12-2021' '14-11-2021' '18-10-2021' '27-04-2022'
 '19-10-2021' '03-04-2022' '13-11-2021' '28-03-2022' '21-10-2021'
 '23-10-2021' '22-01-2022' '26-11-2021' '25-10-2021' '27-10-2021'
 '07-10-2021' '09-10-2021' '26-01-2022' '08-11-2021' '12-10-2021'
 '05-06-2022' '16-03-2022' '14-06-2022' '04-12-2021' '12-01-2022'
 '04-09-2022' '12-12-2021' '05-11-2021' '19-11-2021' '05-10-2021'
 '30-10-2021' '16-06-2022' '03-12-2021' '07-11-2021' '03-10-2021'
 '22-10-2021' '31-10-2021' '16-10-2021' '21-02-2022' '05-09-2022']

EndTime
['23:59:13' '21:31:04' '19:54:29' ... '15:20:28' '11:45:37' '17:36:47']

StartDatetime
['15-09-2022 20:54' '14-09-2022 20:01' '14-09-2022 18:54' ...
 '03-10-2021 13:52' '18-11-2021 11:37' '30-10-2021 17:29']

EndDatetime
['15-09-2022 23:59' '14-09-2022 21:31' '14-09-2022 19:54' ...
 '03-10-2021 14:32' '18-11-2021 11:45' '30-10-2021 17:36']

In [35]:
df["StartDatetime"] = pd.to_datetime(df["StartDatetime"])

In [36]:
df["EndDatetime"] = pd.to_datetime(df["EndDatetime"])

In [37]:
df[["StartDatetime", "EndDatetime"]].dtypes

StartDatetime    datetime64[ns]
EndDatetime      datetime64[ns]
dtype: object

In [39]:
df["Year"] = df["StartDatetime"].dt.year
df["Month"] = df["StartDatetime"].dt.month
df["Month_Name"] = df["StartDatetime"].dt.month_name()

df["Day"] = df["StartDatetime"].dt.day
df["Day_Name"] = df["StartDatetime"].dt.day_name()

df["Hour"] = df["StartDatetime"].dt.hour
df["Week"] = df["StartDatetime"].dt.isocalendar().week

In [41]:
df["Calculated_Duration"] = (
    df["EndDatetime"] - df["StartDatetime"]
).dt.total_seconds() / 60

In [43]:
df[["Duration", "Calculated_Duration"]].head(10)

   Duration  Calculated_Duration
0       185                185.0
1        90                 90.0
2        60                 60.0
3       344                344.0
4       300                300.0
5        70                 70.0
6        60                 60.0
7       494                494.0
8        60                 60.0
9       112                112.0

In [44]:
print("Total Sessions:", len(df))
print("Unique Users:", df["UserID"].nunique())
print("Unique Chargers:", df["ChargerID"].nunique())
print("Total Energy:", df["Demand"].sum())
print("Average Energy:", df["Demand"].mean())
print("Average Duration:", df["Duration"].mean())

Total Sessions: 72843
Unique Users: 2337
Unique Chargers: 2119
Total Energy: 1270576.21
Average Energy: 17.44266724324918
Average Duration: 151.18399846244662

In [42]:
df

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,...,Duration,Demand,Year,Month,Month_Name,Day,Day_Name,Hour,Week,Calculated_Duration
0,0,1,1,hotel,0,15-09-2022,20:54:02,15-09-2022,23:59:13,2022-09-15 20:54:00,...,185,20.36,2022,9,September,15,Thursday,20,37,185.0
1,0,1,1,hotel,0,14-09-2022,20:01:05,14-09-2022,21:31:04,2022-09-14 20:01:00,...,90,10.19,2022,9,September,14,Wednesday,20,37,90.0
2,0,1,1,hotel,0,14-09-2022,18:54:30,14-09-2022,19:54:29,2022-09-14 18:54:00,...,60,6.78,2022,9,September,14,Wednesday,18,37,60.0
3,0,1,1,hotel,0,29-09-2022,18:32:51,30-09-2022,00:16:42,2022-09-29 18:32:00,...,344,37.65,2022,9,September,29,Thursday,18,39,344.0
4,0,1,1,hotel,0,25-09-2022,19:30:15,26-09-2022,00:30:14,2022-09-25 19:30:00,...,300,33.81,2022,9,September,25,Sunday,19,38,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72851,2155,2649,0,public institution,0,27-01-2022,09:54:44,27-01-2022,09:58:57,2022-01-27 09:54:00,...,4,0.50,2022,1,January,27,Thursday,9,4,4.0
72852,2379,2670,0,sightseeing,1,31-10-2021,14:52:11,31-10-2021,15:20:28,2021-10-31 14:52:00,...,28,16.53,2021,10,October,31,Sunday,14,43,28.0
72853,2388,2670,0,sightseeing,1,03-10-2021,13:52:14,03-10-2021,14:32:13,2021-10-03 13:52:00,...,40,12.20,2021,10,October,3,Sunday,13,39,40.0
72854,2388,2671,0,company,1,18-11-2021,11:37:44,18-11-2021,11:45:37,2021-11-18 11:37:00,...,8,3.80,2021,11,November,18,Thursday,11,46,8.0
72855,2388,2671,0,company,1,30-10-2021,17:29:02,30-10-2021,17:36:47,2021-10-30 17:29:00,...,8,3.67,2021,10,October,30,Saturday,17,43,7.0

In [48]:
#Unique Users
df["UserID"].nunique()

2337

In [46]:
# Unique Charger
df["ChargerID"].nunique()

2119

In [47]:
# Total Energy Demand
df["Demand"].sum()

np.float64(1270576.21)

In [49]:
# Average Energy Per Session
df["Demand"].mean()

np.float64(17.44266724324918)

In [50]:
# Average Charging Duration
df["Duration"].mean(
    
)

np.float64(151.18399846244662)

In [ ]:
##=============================================================Dashboard==================================================================

In [ ]:
st.set_page_config(
    page_title="EV Charging Inteligence",
    page_icon="⚡",
    layout="wide"
)


st.sidebar.header("Globel Filter")
st.sidebar.caption("Apply Filters From Given Filters")


# Date Range
date_range = st.sidebar.date_input(
    "Date Range",
    value=(
        df["StartDatetime"].min().date(),
        df["StartDatetime"].max().date()
    )
)

# Location
location = st.sidebar.multiselect(
    "Location",
    options=sorted(df["Location"].dropna().unique()),
    default=sorted(df["Location"].dropna().unique())
)


# Charger Type
charger_type = st.sidebar.multiselect(
    "Charger Type",
    options=sorted(df["ChargerType"].dropna().unique()),
    default=sorted(df["ChargerType"].dropna().unique())
)



# AC / DC
ac_dc = st.sidebar.multiselect(
    "Charging Type",
    options=sorted(df["ChargerACDC"].dropna().unique()),
    default=sorted(df["ChargerACDC"].dropna().unique())
)



# Charger Capacity
capacity = st.sidebar.multiselect(
    "Charger Capacity",
    options=sorted(df["ChargerCapacity"].dropna().unique()),
    default=sorted(df["ChargerCapacity"].dropna().unique())
)



# Charger Company
company = st.sidebar.multiselect(
    "Charger Company",
    options=sorted(df["ChargerCompany"].dropna().unique()),
    default=sorted(df["ChargerCompany"].dropna().unique())
)









# DF Copy
filtered_df = df.copy()



# Date Filter
start_date = pd.to_datetime(date_range[0])
end_date = pd.to_datetime(date_range[1]) + pd.Timedelta(days=1)

filtered_df = filtered_df[
    (filtered_df["StartDatetime"] >= start_date) &
    (filtered_df["StartDatetime"] < end_date)
]



# Location Filter
filtered_df = filtered_df[
    filtered_df["Location"].isin(location)
]



# Charger Filter
filtered_df = filtered_df[
    filtered_df["ChargerType"].isin(charger_type)
]



# AC/DC Filter 
filtered_df = filtered_df[
    filtered_df["ChargerACDC"].isin(ac_dc)
]


#  Charger Capacity
filtered_df = filtered_df[
    filtered_df["ChargerCapacity"].isin(capacity)
]


# Company 
filtered_df = filtered_df[
    filtered_df["ChargerCompany"].isin(company)
]

In [ ]:
@st.cache_data
def load_data():
    df = pd.read_csv("data/EV_Charging.csv")

    df["StartDatetime"] = pd.to_datetime(df["StartDatetime"])
    df["EndDatetime"] = pd.to_datetime(df["EndDatetime"])

    return df


df = load_data()